<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://test" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://test" xmlns:intf="http://test" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://test" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="unenrollFor">
    <complexType/>
   </element>
   <element name="unenrollForResponse">
    <complexType/>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="unenrollForRequest">

      <wsdl:part element="impl:unenrollFor" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="unenrollForResponse">

      <wsdl:part element="impl:unenrollForResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="UniversityServiceTest">

      <wsdl:operation name="unenrollFor">

         <wsdl:input message="impl:unenrollForRequest" name="unenrollForRequest">

       </wsdl:input>

         <wsdl:output message="impl:unenrollForResponse" name="unenrollForResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="UniversityServiceTestSoapBinding" type="impl:UniversityServiceTest">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="unenrollFor">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="unenrollForRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="unenrollForResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="UniversityServiceTestService">

      <wsdl:port binding="impl:UniversityServiceTestSoapBinding" name="UniversityServiceTest">

         <wsdlsoap:address location="http://localhost:8081/UniversityRecordSystem/services/UniversityServiceTest"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
